title: Wax Legal
author: 
  name: mjc
description: Making sausage out of the future

baseurl: /
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
  skin: solarized
  
  show_excerpts: true

  social_links:
    - title: Wax Legal on Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/wax.legal"

  nav_pages:
    - about.md
